import 'package:flutter/material.dart';

/// Offline icon resolution for the suggested-sites list.
///
/// The suggestions list MUST render without any network request (see
/// openspec spec `configurable-suggested-sites` SUGGEST-007). This module
/// resolves a suggestion's icon from two purely-local sources, in order:
///
/// 1. A committed bundled asset under `assets/suggested_icons/<host>.png`,
///    listed in [kBundledIconHosts]. These are pinned inputs regenerated by
///    `scripts/regen_suggested_icons.sh` and committed, never fetched during
///    the build (a build-time fetch would break reproducibility and move the
///    third-party contact to the build server).
/// 2. A locally-rendered monogram (first letter on a host-derived color) when
///    no bundled asset exists. This is the default: it ships no third-party
///    logo binaries (trademark-safe for F-Droid) and is fully deterministic.

/// Hosts that have a committed icon under `assets/suggested_icons/<host>.png`.
///
/// Populated by `scripts/regen_suggested_icons.sh`. Empty means every
/// suggestion renders as a monogram. Keep entries lowercase and `www.`-stripped
/// to match [normalizeIconHost].
const Set<String> kBundledIconHosts = {
  'bsky.app',
  'codeberg.org',
  'gitea.com',
  'gitlab.com',
  'huggingface.co',
  'mastodon.social',
};

const String _assetDir = 'assets/suggested_icons';

/// Normalize a host for bundled-asset lookup: lowercase, strip a leading
/// `www.`. Mirrors the keys written by the regeneration script.
String normalizeIconHost(String host) {
  var h = host.toLowerCase();
  if (h.startsWith('www.')) h = h.substring(4);
  return h;
}

/// The committed asset path for [host], or null when none is bundled.
String? bundledIconAssetFor(String host) {
  final h = normalizeIconHost(host);
  return kBundledIconHosts.contains(h) ? '$_assetDir/$h.png' : null;
}

/// Deterministic background color for a monogram, derived from [seed] so the
/// same host always gets the same color without storing anything.
Color monogramColor(String seed) {
  var hash = 0;
  for (final unit in seed.codeUnits) {
    hash = (hash * 31 + unit) & 0x7fffffff;
  }
  return Color.fromARGB(0xff, 96 + hash % 96, 96 + (hash >> 8) % 96,
      96 + (hash >> 16) % 96);
}

/// The single uppercase letter to show in a monogram for [label]/[host].
String monogramLetter({String? label, required String host}) {
  final source = (label != null && label.trim().isNotEmpty)
      ? label.trim()
      : normalizeIconHost(host);
  for (final rune in source.runes) {
    final ch = String.fromCharCode(rune);
    if (RegExp(r'[A-Za-z0-9]').hasMatch(ch)) return ch.toUpperCase();
  }
  return '?';
}
