// Tier 1 — end-to-end parser → shim assertions.
//
// Other content-blocker tests check rule shapes one at a time; this
// one feeds a curated EasyList-style sample (test/fixtures/easylist_
// sample.txt) through the real Dart parser and asserts that the
// resulting cosmetic shim hides representative ad markup on a
// LinkedIn-shaped page while leaving real article content alone.
//
// The fixture is regenerated by tool/dump_shim_js.dart; the drift
// check (test/js_fixtures_drift_test.dart) keeps the on-disk JS in
// sync with the rule sample. If you change the sample, re-run the
// dumper and update the assertions below to match.

const test = require('node:test');
const assert = require('node:assert/strict');
const { makeDom, runInDom, readFixture } = require('./helpers/load_shim');

const SAMPLE = readFixture('content_blocker/easylist_sample_linkedin.js');

// HTML modeled on a LinkedIn feed page. Every element has an `id` so
// assertions read clearly and the markup hits every rule shape in the
// sample:
//   * Generic class cosmetic (.advert, .ad-banner, .sponsored-content)
//   * Attribute cosmetic (div[data-ad-slot])
//   * href*= cosmetic
//   * Standard CSS :has()  (#article-with-adsbygoogle)
//   * :-abp-has() rewrite  (#feed-item-ad-tag)
//   * :has-text()          (#notice-sponsored)
//   * :contains()          (#story-advert)
//   * Domain cosmetic      (#linkedin-ad)
//   * Domain :-abp-has()   (#feed-with-actor)
//   * Domain :-abp-contains text rule  (#actor-promoted, #actor-sponsored)
//   * Plus controls that should stay visible (#article-clean, etc.)
const LINKEDIN_HTML = `<!doctype html><html><body>
  <div class="advert" id="advert-block">generic ad</div>
  <div class="ad-banner" id="ad-banner-block">ad banner</div>
  <div class="sponsored-content" id="sponsored-content-block">sponsored</div>
  <div data-ad-slot="123" id="ad-slot">slot ad</div>
  <a href="https://doubleclick.net/x" id="dc-link">tracker</a>

  <div class="article" id="article-with-adsbygoogle">
    <div class="adsbygoogle">google ad</div>
  </div>
  <div class="article" id="article-clean">
    <p>Real article body</p>
  </div>

  <div class="feed-item" id="feed-item-ad-tag">
    <span class="ad-tag">x</span>body
  </div>
  <div class="feed-item" id="feed-item-clean">no ad-tag here</div>

  <span class="notice" id="notice-sponsored">Sponsored content here</span>
  <span class="notice" id="notice-clean">Regular notice</span>

  <p class="story-body" id="story-advert">An Advertisement appears here</p>
  <p class="story-body" id="story-clean">Pure editorial content</p>

  <div class="feed-shared-update-v2--ad" id="linkedin-ad">linkedin native ad</div>

  <div class="feed-shared-update-v2" id="feed-with-actor">
    <span class="feed-shared-actor__sub-description">subdescription</span>
    body
  </div>
  <div class="feed-shared-update-v2" id="feed-without-actor">no subdescription</div>

  <div class="feed-shared-actor" id="actor-promoted">Promoted by Acme Inc</div>
  <div class="feed-shared-actor" id="actor-sponsored">Sponsored update</div>
  <div class="feed-shared-actor" id="actor-clean">John Smith - 1d</div>

  <div class="cross-site-ad" id="cross-site">cross-site ad (not in scope on linkedin.com)</div>
  <p id="real-content">This is real article content the reader cares about.</p>
</body></html>`;

function load() {
  const dom = makeDom({ url: 'https://linkedin.com/feed', html: LINKEDIN_HTML });
  runInDom(dom, SAMPLE);
  return dom;
}

function cs(dom, id) {
  return dom.window
    .getComputedStyle(dom.window.document.getElementById(id))
    .display;
}

// ---------- Generic cosmetic (early CSS) ----------

test('easylist sample: generic class selectors hide ad markup', () => {
  const dom = load();
  for (const id of ['advert-block', 'ad-banner-block', 'sponsored-content-block']) {
    assert.equal(cs(dom, id), 'none', `#${id} must hide via generic class rule`);
  }
});

test('easylist sample: attribute selector hides [data-ad-slot]', () => {
  const dom = load();
  assert.equal(cs(dom, 'ad-slot'), 'none');
});

test('easylist sample: href*= attribute selector hides doubleclick.net link',
  () => {
    const dom = load();
    assert.equal(cs(dom, 'dc-link'), 'none');
  });

// ---------- :has() (native + :-abp-has() rewrite) ----------

test('easylist sample: standard CSS :has() hides article wrapping adsbygoogle',
  () => {
    const dom = load();
    assert.equal(cs(dom, 'article-with-adsbygoogle'), 'none',
      'div.article:has(div.adsbygoogle) must hide via CSS engine');
    assert.notEqual(cs(dom, 'article-clean'), 'none',
      'article without adsbygoogle must stay visible');
  });

test('easylist sample: :-abp-has() rewritten to :has() hides matching parents',
  () => {
    const dom = load();
    assert.equal(cs(dom, 'feed-item-ad-tag'), 'none',
      'div.feed-item with .ad-tag descendant must hide (post :-abp-has rewrite)');
    assert.notEqual(cs(dom, 'feed-item-clean'), 'none',
      'feed-item without .ad-tag must stay visible');
  });

// ---------- Domain-specific cosmetic ----------

test('easylist sample: linkedin-specific class hides on linkedin.com', () => {
  const dom = load();
  assert.equal(cs(dom, 'linkedin-ad'), 'none');
});

test('easylist sample: linkedin-specific :-abp-has hides feed updates with actor',
  () => {
    const dom = load();
    assert.equal(cs(dom, 'feed-with-actor'), 'none',
      'div.feed-shared-update-v2:has(.feed-shared-actor__sub-description) must hide');
    assert.notEqual(cs(dom, 'feed-without-actor'), 'none',
      'feed update without sub-description must stay visible');
  });

// ---------- Text rules (:has-text / :contains / :-abp-contains) ----------

test('easylist sample: :has-text(Sponsored) hides matching span.notice', () => {
  const dom = load();
  assert.equal(dom.window.document.getElementById('notice-sponsored').style.display,
    'none');
  assert.equal(dom.window.document.getElementById('notice-clean').style.display, '');
});

test('easylist sample: :contains(Advertisement) hides matching p.story-body',
  () => {
    const dom = load();
    assert.equal(dom.window.document.getElementById('story-advert').style.display,
      'none');
    assert.equal(dom.window.document.getElementById('story-clean').style.display, '');
  });

test('easylist sample: linkedin :-abp-contains text rule with /A|B/ alternation',
  () => {
    const dom = load();
    const doc = dom.window.document;
    assert.equal(doc.getElementById('actor-promoted').style.display, 'none',
      'feed-shared-actor with "Promoted" must hide');
    assert.equal(doc.getElementById('actor-sponsored').style.display, 'none',
      'feed-shared-actor with "Sponsored" must hide');
    assert.equal(doc.getElementById('actor-clean').style.display, '',
      'feed-shared-actor with neither pattern must stay visible');
  });

// ---------- Negative cases ----------

test('easylist sample: real article content is not touched', () => {
  const dom = load();
  assert.notEqual(cs(dom, 'real-content'), 'none',
    'arbitrary article paragraph must remain visible');
});

test('easylist sample: cross-site rule scoped to other hosts does not fire here',
  () => {
    // The sample has `example.com,test.com##.cross-site-ad`. We collected
    // rules for linkedin.com, so .cross-site-ad must NOT be in the sheet.
    // Element on the page must therefore stay visible.
    const dom = load();
    assert.notEqual(cs(dom, 'cross-site'), 'none',
      'cross-site-only rule must not leak into linkedin.com fixture');
  });

// ---------- Late-mutation reactivity ----------

test('easylist sample: late-added matching subtree hides via :has() reactivity',
  async () => {
    // Strict improvement over the pre-2026 runtime sweep: the CSS
    // engine re-evaluates :has() when descendants change. Real-world
    // value is feed virtualization on linkedin / cnn / sites where ad
    // wrappers swap children long after page load.
    const dom = load();
    const doc = dom.window.document;
    const lateFeed = doc.createElement('div');
    lateFeed.className = 'feed-item';
    lateFeed.id = 'late-feed';
    doc.body.appendChild(lateFeed);
    assert.notEqual(dom.window.getComputedStyle(lateFeed).display, 'none',
      'pre-condition: empty feed-item is visible');
    const tag = doc.createElement('span');
    tag.className = 'ad-tag';
    lateFeed.appendChild(tag);
    await new Promise((r) => setTimeout(r, 10));
    assert.equal(dom.window.getComputedStyle(lateFeed).display, 'none',
      'CSS :has() engine must hide the feed-item after .ad-tag is appended');
  });

test('easylist sample: late-inserted Promoted post hides via observer', async () => {
  const dom = load();
  const doc = dom.window.document;
  const late = doc.createElement('div');
  late.className = 'feed-shared-actor';
  late.id = 'late-actor';
  late.textContent = 'Promoted by Late Co';
  doc.body.appendChild(late);
  await new Promise((r) => setTimeout(r, 100));
  assert.equal(late.style.display, 'none',
    'observer must re-run text rules on later inserts');
});
