// Tier 1 — jsdom assertions for uBO `:style(declarations)` rules.
//
// The parser converts `##selector:style(decls)` and
// `domain##selector:style(decls)` into StyleRule entries instead of
// adding the selector to the `display:none` pile. The shim then emits
// `selector { decls }` alongside the regular hide rules in the same
// early `<style>` tag.
//
// Why jsdom matters here: the parser test asserts the parsed shape;
// the shim builder test asserts the JS string shape; only jsdom can
// confirm that the browser's CSS engine actually applies the
// declarations to a real element AND that hiding selectors continue
// to fire from the same <style> tag without conflict.
//
// Companion fixture: test/js_fixtures/content_blocker/style_rules.js
// generated by tool/dump_shim_js.dart from a synthetic input that
// mixes one `display:none` selector with two `:style(...)` rules. If
// the fixture drifts, the drift check in
// test/js_fixtures_drift_test.dart will fail before this test does.

const test = require('node:test');
const assert = require('node:assert/strict');
const { makeDom, runInDom, readFixture } = require('./helpers/load_shim');

const STYLE_RULES = readFixture('content_blocker/style_rules.js');

const HTML = `<!doctype html><html><body>
  <div class="always-hidden" id="hidden">should be display:none</div>
  <div class="shrunk-banner" id="shrunk">banner</div>
  <div class="faded-promo" id="faded">faded promo</div>
  <div class="untouched" id="control">left alone</div>
</body></html>`;

function load() {
  const dom = makeDom({ html: HTML });
  runInDom(dom, STYLE_RULES);
  return dom;
}

test('style_rules: display:none selector hides as before', () => {
  const dom = load();
  const cs = dom.window.getComputedStyle(
    dom.window.document.getElementById('hidden'));
  assert.equal(cs.display, 'none',
    'plain selectors must still hide via the same <style> tag');
});

test('style_rules: :style(height: 1px) is applied to matching elements', () => {
  const dom = load();
  const cs = dom.window.getComputedStyle(
    dom.window.document.getElementById('shrunk'));
  assert.equal(cs.height, '1px',
    ':style(height: 1px !important) must reach the CSS engine');
});

test('style_rules: stylesheet emits the right declarations', () => {
  // jsdom does not paint, so the strongest behavioural signal is the
  // contents of the injected <style> tag combined with a positive
  // computed-style read on the matching element. Asserting both
  // proves the parser→shim→CSS pipeline survived.
  const dom = load();
  const styleEl = dom.window.document.getElementById(
    '_webspace_content_blocker_style');
  assert.ok(styleEl, 'shim must have inserted its <style> tag');
  const css = styleEl.textContent;
  assert.match(css, /\.always-hidden \{ display: none !important; \}/);
  assert.match(css, /\.shrunk-banner \{ height: 1px !important \}/);
  assert.match(css, /\.faded-promo \{ opacity: 0\.1 !important \}/);
});

test('style_rules: :style(opacity: 0.1) is applied without hiding', () => {
  const dom = load();
  const el = dom.window.document.getElementById('faded');
  const cs = dom.window.getComputedStyle(el);
  assert.equal(cs.opacity, '0.1',
    'opacity declaration must reach the CSS engine');
  assert.notEqual(cs.display, 'none',
    ':style() must NOT collateral-hide the element');
});

test('style_rules: untouched element keeps its defaults', () => {
  const dom = load();
  const cs = dom.window.getComputedStyle(
    dom.window.document.getElementById('control'));
  assert.notEqual(cs.display, 'none');
  assert.notEqual(cs.opacity, '0.1');
});

test('style_rules: late-added matching element picks up :style() reactively',
  async () => {
    // Same property the spec promises for cosmetic selectors —
    // because :style() rules ride the early <style> tag, they
    // benefit from the CSS engine's automatic re-match for free.
    const dom = load();
    const doc = dom.window.document;
    const late = doc.createElement('div');
    late.id = 'late-shrunk';
    late.className = 'shrunk-banner';
    doc.body.appendChild(late);
    await new Promise((r) => setTimeout(r, 10));
    const cs = dom.window.getComputedStyle(late);
    assert.equal(cs.height, '1px',
      'CSS engine must apply :style() to elements added after injection');
  });
