plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace "org.codeberg.theoden8.webspace.testprovider"
    compileSdk 36

    defaultConfig {
        applicationId "org.codeberg.theoden8.webspace.testprovider"
        // CredentialProviderService is API 34.
        minSdk 34
        targetSdk 35
        versionCode 1
        versionName "1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    implementation "androidx.credentials:credentials:1.5.0"
}
