// Generates the two-tone looping WebM used as a *video* virtual-camera
// source by integration_test/camera_test.dart.
//
//   node tool/generate_camera_video_fixture.js
//
// Output: integration_test/fixtures/virtual_camera_video.dart — a base64
// const, because the emulator tier runs on-device where the repo's files
// are not readable and adding the clip to pubspec `assets:` would ship it
// inside the production app.
//
// Encoded with Chromium's own MediaRecorder (canvas.captureStream ->
// VP8/WebM) so no ffmpeg is needed; the repo's Puppeteer browser is the
// only dependency. The clip alternates two colours every ~500 ms so the
// test can prove the source is really LOOPING rather than frozen on a
// single decoded frame.

const fs = require('node:fs');
const path = require('node:path');
const puppeteer = require('puppeteer');

const OUT = path.resolve(
  __dirname, '..', 'integration_test', 'fixtures', 'virtual_camera_video.dart');

// Kept in sync with the constants in integration_test/camera_test.dart.
const COLOR_A = [0x1E, 0xC8, 0x7A]; // green
const COLOR_B = [0xC8, 0x1E, 0x9B]; // magenta

(async () => {
  const browser = await puppeteer.launch({
    headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  const page = await browser.newPage();
  await page.goto('about:blank', { waitUntil: 'load' });

  const base64 = await page.evaluate(async (a, b) => {
    const canvas = document.createElement('canvas');
    canvas.width = 160;
    canvas.height = 120;
    const ctx = canvas.getContext('2d');
    const stream = canvas.captureStream(10);
    const rec = new MediaRecorder(stream, {
      mimeType: 'video/webm;codecs=vp8',
      videoBitsPerSecond: 100000,
    });
    const chunks = [];
    rec.ondataavailable = (e) => { if (e.data.size) chunks.push(e.data); };
    const done = new Promise((res) => { rec.onstop = res; });

    const paint = (c) => {
      ctx.fillStyle = `rgb(${c[0]},${c[1]},${c[2]})`;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
    };

    paint(a);
    rec.start();
    // 1s clip: 500ms of each colour.
    await new Promise((r) => setTimeout(r, 500));
    paint(b);
    await new Promise((r) => setTimeout(r, 500));
    rec.stop();
    await done;

    const blob = new Blob(chunks, { type: 'video/webm' });
    const buf = await blob.arrayBuffer();
    const bytes = new Uint8Array(buf);
    let bin = '';
    for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
    return btoa(bin);
  }, COLOR_A, COLOR_B);

  await browser.close();

  const dart = `// GENERATED by tool/generate_camera_video_fixture.js — do not edit.
//
// A ~1s VP8/WebM clip alternating two solid colours every ~500ms, used as
// the *video* virtual-camera source in integration_test/camera_test.dart.
// Committed (rather than generated at test time) because the Android
// emulator tier has no browser to encode it and the clip must not ship in
// the production app's assets.
//
// Regenerate: node tool/generate_camera_video_fixture.js

/// Solid colours the clip alternates between, as RGB.
const List<int> kVirtualCameraVideoColorA = [${COLOR_A.join(', ')}];
const List<int> kVirtualCameraVideoColorB = [${COLOR_B.join(', ')}];

/// The clip as a \`data:\` URL, ready to hand to \`VirtualCameraSource\`.
const String kVirtualCameraVideoDataUrl =
    'data:video/webm;base64,'
    '${base64}';
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, dart);
  console.log(`wrote ${OUT} (${base64.length} base64 chars)`);
})().catch((e) => { console.error(e); process.exit(1); });
