# Snapfile for iOS screenshot generation
# For more information about the Snapfile, see:
# https://docs.fastlane.tools/actions/snapshot/

# A list of devices you want to take screenshots for
devices([
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone SE (3rd generation)",
  "iPad Pro (12.9-inch) (6th generation)",
  "iPad Pro (11-inch) (4th generation)"
])

# A list of supported languages
languages([
  "en-US"
  # Add more languages as needed:
  # "de-DE",
  # "es-ES",
  # "fr-FR",
  # "it-IT",
  # "ja-JP",
  # "ko-KR",
  # "pt-BR",
  # "zh-Hans"
])

# The name of the scheme which contains the UI Tests
scheme("Runner")

# Where should the resulting screenshots be stored?
# Store in root fastlane directory to match Android setup
output_directory("../../fastlane/screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Arguments to pass to the app on launch
# launch_arguments(["-favColor red"])

# Choose which project/workspace to use
# Path relative to ios/ directory (where fastlane runs from)
workspace("Runner.xcworkspace")

# Specify project as fallback
project("Runner.xcodeproj")

# For more information about all available options run
# fastlane action snapshot

# Remove the '#' to override the status bar
override_status_bar(true)

# Disable showing the simulator's status bar while taking screenshots
# hide_simulator_status_bar(false)

# Add dark mode screenshots
# dark_mode(true)
