// GENERATED by tool/generate_camera_video_fixture.js — do not edit.
//
// A ~1s VP8/WebM clip alternating two solid colours every ~500ms, used as
// the *video* virtual-camera source in integration_test/camera_test.dart.
// Committed (rather than generated at test time) because the Android
// emulator tier has no browser to encode it and the clip must not ship in
// the production app's assets.
//
// Regenerate: node tool/generate_camera_video_fixture.js

/// Solid colours the clip alternates between, as RGB.
const List<int> kVirtualCameraVideoColorA = [30, 200, 122];
const List<int> kVirtualCameraVideoColorB = [200, 30, 155];

/// The clip as a `data:` URL, ready to hand to `VirtualCameraSource`.
const String kVirtualCameraVideoDataUrl =
    'data:video/webm;base64,'
    'GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQRChYECGFOAZwEAAAAAAAHdEU2bdLlNu4tTq4QVSalmU6yBbk27i1OrhBZUrmtTrIGTTbuLU6uEH0O2dVOsgcFNu4xTq4QcU7trU6yCAcvsrgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmoCrXsYMPQkBEiYRD+ik3TYCGQ2hyb21lV0GGQ2hyb21lFlSua6mup9eBAXPFh3ou+jIzO8yDgQFV7oEBhoVWX1ZQOOCKsIGguoF4U8CBAR9DtnUBAAAAAAAA/ueBAKBAmKHMgQAAAJAGAJ0BKqAAeAAJBwiFhYiZhIgwggJ08j6taYaovLXnDSa5zhpNc5w0muc4aTXOcNJrnOGk1znDSa5zhmwA/cVrB6+8odiTAHWhx6bF7oEBpcBQBgCdASqgAHgACocIhYWImYSIOAIABiIPBRCcUtKhOKWlQnFLSoTilpUJxS0qE4paVCcUtKhOKWlQmwD+664AoN6hu4EB9ABxBAAkEUgAGAzQyTi7lHADZBwFQHAVsYCtYwFaxgK1jAVrGArQAP7XleVerzKv8UPNb2DtKUwAdaGbppnugQGllBECACoRwAAYABhYL/QACICBDLAA+4EAHFO7a427i7OBALeG94EB8YHB';
