// SPDX-License-Identifier: MPL-2.0
// Auto-generated by cbindgen. Do not edit by hand.
// Regenerate with `cbindgen --config cbindgen.toml --crate webspace_adblock --output ../../include/webspace_adblock.h`.

#ifndef WEBSPACE_ADBLOCK_H
#define WEBSPACE_ADBLOCK_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Opaque engine handle. Heap-allocated via `Box`; the C side sees
 * only a `*mut Engine` and never dereferences it. cbindgen prefixes
 * this to `WsEngine` in the generated header.
 */
typedef struct WsEngine WsEngine;

/**
 * Parse [rules_text] (a UTF-8 filter list, lines separated by `\n`)
 * into a new engine. Returns null on UTF-8 error or panic.
 *
 * `rules_text` must point to `len` bytes. Caller retains ownership;
 * we copy into the engine.
 */
struct WsEngine *ws_engine_new(const char *rules_text, uintptr_t len);

/**
 * Drop the engine. Safe to call with a null pointer (no-op).
 */
void ws_engine_free(struct WsEngine *engine);

/**
 * Block-decision check. Mirrors `adblock::Engine::check_network_request`
 * but with C-friendly arguments.
 *
 * `source_url` and `request_type` may be empty strings (length 0,
 * any pointer); the engine will degrade gracefully — `request_type`
 * of "" is treated as "other".
 *
 * Returns:
 *   * `1` — request matched a block rule, no exception in effect
 *   * `0` — request allowed (no match, or matched + exception)
 *   * `-1` — bad arguments / panic
 */
int32_t ws_engine_check_url(struct WsEngine *engine,
                            const char *url,
                            uintptr_t url_len,
                            const char *source_url,
                            uintptr_t source_url_len,
                            const char *request_type,
                            uintptr_t request_type_len);

/**
 * Per-URL cosmetic resources, JSON-encoded. The shape is:
 * ```json
 * {
 *   "hide_selectors": ["sel", ...],
 *   "style_selectors": {".sel": ["height:1px !important", ...], ...},
 *   "exceptions": ["sel", ...],
 *   "injected_script": "...",
 *   "generichide": false
 * }
 * ```
 * Caller must free the returned pointer with [`ws_string_free`].
 * Returns null on error.
 */
char *ws_engine_cosmetic_resources_json(struct WsEngine *engine,
                                        const char *url,
                                        uintptr_t url_len);

/**
 * Free a string returned by this library. Safe with null.
 */
void ws_string_free(char *s);

/**
 * Get the engine's library version string. Useful for debugging
 * "which adblock-rust am I running" without rebuilding.
 * Caller must free with [`ws_string_free`].
 */
char *ws_engine_version(void);

#endif  /* WEBSPACE_ADBLOCK_H */
